"""Utilities for working with `Package.swift` files."""

_PACKAGE_SWIFT_NAME = "Package.swift"

def _create_merged_package_swift(*, module_ctx, pkg_files, tools_version):
    """Creates a merged `Package.swift` file from the specified `Package.swift` files.

    The "merged" Package.swift file simply contains a local `package(path:)` usage for \
    each of the specified `Package.swift` files.

    Args:
        module_ctx: An instance of `module_ctx`.
        pkg_files: A `list` of `struct(name = str, path = path)` objects representing \
            the `Package.swift` files and the name of the module the package is for.
        tools_version: The Swift tools version used by the root module.

    Returns:
        A `path` object representing the merged `Package.swift` file.
    """

    dependencies = []
    for pkg_file in pkg_files:
        dependencies.append("""\
        .package(name: "{name}", path: \"{path}\")
""".format(name = pkg_file.name, path = pkg_file.path))

    content = """
// swift-tools-version: {tools_version}

// NOTE: THIS FILE IS AUTO-GENERATED BY rules_swift_package_manager. DO NOT EDIT.

import PackageDescription

let package = Package(
    name: "merged",
    dependencies: [
{dependencies_str}
    ]
)
    """.format(
        tools_version = tools_version,
        dependencies_str = ",\n".join(dependencies),
    )

    module_ctx.file(_PACKAGE_SWIFT_NAME, content)
    return module_ctx.path(_PACKAGE_SWIFT_NAME)

swift_package_files = struct(
    merge = _create_merged_package_swift,
)
