#!/usr/bin/env bash

# This script is called by Renovate as a post-upgrade task. It installs
# Bazelisk and then executes tidy in workspaces that have modifications from
# the Renovate upgrade process.

set -o errexit -o nounset -o pipefail

# Install Bazelisk, if not found
if which &>/dev/null bazelisk; then
  echo "Bazelisk was found."
  bazelisk="bazelisk"
else
  echo "Bazelisk was not found. Installing..."
  npm install -g @bazel/bazelisk
  bazelisk="$HOME/node_modules/@bazel/bazelisk/bazelisk-linux_amd64"
fi

# Install build tools
if which &>/dev/null clang; then
  echo "clang was found."
else
  echo "clang was not found. Installing build-essential..."
  # install-tool clang 12.0.0
  install-tool clang-12 12.0.0
fi

# Execute tidy for workspaces with modifications The export of CC and the
# --action_env=PATH are specific to running this repository on Linux.
export CC=clang
"${bazelisk}" run --action_env=PATH //:tidy_modified
