package cmd

import (
	"fmt"

	"github.com/spf13/cobra"
)

// createCmd represents the create command
var createCmd = &cobra.Command{
	Use:   "create [<pkg_info_path>...]",
	Short: "Create a Swift dependencies index file.",
	Long: `Create a Swift dependencies index JSON file from pkg_info.json
files as generated by rules_swift_package_manager.`,
	Run: func(cmd *cobra.Command, args []string) {
		// TODO(chuck): Implement the Swift deps index
		fmt.Println("create called")
	},
}

func init() {
	rootCmd.AddCommand(createCmd)

	// Here you will define your flags and configuration settings.

	// Cobra supports Persistent Flags which will work for this command
	// and all subcommands, e.g.:
	// createCmd.PersistentFlags().String("foo", "", "A help for foo")

	// Cobra supports local flags which will only run when this command
	// is called directly, e.g.:
	// createCmd.Flags().BoolP("toggle", "t", false, "Help message for toggle")
}
