package cmd

import (
	"fmt"
	"os"

	"github.com/cgrindel/rules_swift_package_manager/gazelle/internal/swift"
	"github.com/cgrindel/rules_swift_package_manager/gazelle/internal/swiftpkg"
	"github.com/spf13/cobra"
)

const dependencyIndexPerms = 0666

var outputPath string

// createCmd represents the create command
var createCmd = &cobra.Command{
	Use:   "create [<pkg_info_path>...]",
	Short: "Create a Swift dependencies index file.",
	Long: `Create a Swift dependencies index JSON file from pkg_info.json
files as generated by rules_swift_package_manager.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		di := swift.NewDependencyIndex()
		for _, pkgInfoPath := range args {
			pkgInfoJSON, err := os.ReadFile(pkgInfoPath)
			if err != nil {
				return err
			}
			pkgInfo, err := swiftpkg.NewPackageInfoFromJSON(pkgInfoJSON)
			if err != nil {
				return err
			}
			if err := indexSwiftPackage(di, pkgInfo); err != nil {
				return err
			}
		}
		diJSON, err := di.JSON()
		if err != nil {
			return err
		}
		if outputPath != "" {
			if err := os.WriteFile(outputPath, diJSON, dependencyIndexPerms); err != nil {
				return err
			}
		} else {
			fmt.Println(string(diJSON))
		}
		return nil
	},
}

func init() {
	rootCmd.AddCommand(createCmd)
	createCmd.Flags().StringVarP(
		&outputPath, "output", "o", "", "The path where to write the Swift index file.")
}

func indexSwiftPackage(di *swift.DependencyIndex, pkgInfo *swiftpkg.PackageInfo) error {
	pkgIdentity := pkgInfo.Name
	bzlRepo := swift.NewBazelRepo(pkgIdentity, pkgInfo, nil)
	if err := di.IndexBazelRepo(bzlRepo); err != nil {
		return err
	}
	di.AddDirectDependency(pkgIdentity)
	return nil
}
