name: Build and Test
description: Common build and test steps.

runs:
  using: composite
  steps:
    - name: Ensure everything is tidy
      shell: bash
      run: |
        bazelisk run //:tidy_check

    - name: Execute Tests
      shell: bash
      run: |
        bazelisk test //... 

    - name: Execute Integration Tests
      shell: bash
      run: |
        bazelisk test //:all_integration_tests

