#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail

# Use the Bazel binary specified by the integration test. Otherwise, fall back
# to bazel.
bazel="${BIT_BAZEL_BINARY:-bazel}"

# Ensure that the aliased swift-log module and the first-party Logging module
# coexist in one binary.
"${bazel}" test //...
"${bazel}" run //:module_aliases_example
