#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail

# Use the Bazel binary specified by the integration test. Otherwise, fall back
# to bazel.
bazel="${BIT_BAZEL_BINARY:-bazel}"

# Ensure that the C library with a commented modulemap builds and runs.
"${bazel}" test //...
"${bazel}" run //:modulemap_comments_example
