name: Configure bzlmod

inputs:
  enabled:
    description: Boolean value that specifies whether bzlmod should be enabled.
    required: true

runs:
  using: composite
  steps:
    - name: Enable bzmod
      if: inputs.enabled == 'true'
      shell: bash
      run: |
        cat >> "shared.bazelrc" <<EOF
        # Override earlier settings
        common --enable_bzlmod
        build --@cgrindel_bazel_starlib//bzlmod:enabled
        EOF
    - name: Disable bzmod
      if: inputs.enabled != 'true'
      shell: bash
      run: |
        cat >> "shared.bazelrc" <<EOF
        # Override earlier settings
        common --noenable_bzlmod
        build --no@cgrindel_bazel_starlib//bzlmod:enabled
        EOF
