name: Set Up macOS Runner
description: Prepare macOS runner to execute tests.

inputs:
  repo_name:
    description: The name of the GitHub repo.
    required: true
  test_target:
    description: The test target to execute.
    default: ''

runs:
  using: composite
  steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.3'
    - name: Confirm Xcode Version
      shell: bash
      run: |
        # Print used Xcode version
        xcode-select -print-path
        xcodebuild -version
    - uses: cgrindel/gha_set_up_bazel@v1
      with:
        repo_name: ${{ inputs.repo_name }}
    # As of macos-13 runner, go was not on the PATH. This resulted in bazel run 
    # //:go_update_repos failing.
    - uses: actions/setup-go@v5
      with:
        go-version: ">=1.20.0"
