name: Set Up macOS Runner
description: Prepare macOS runner to execute tests.

inputs:
  repo_name:
    description: The name of the GitHub repo.
    required: true
  test_target:
    description: The test target to execute.
    default: ''

runs:
  using: composite
  steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.4'
        # xcode-version: '15.2'
    # - name: Override Xcode Version
      # shell: bash
      # run: |
        # # GH762: Investigate why these examples timeout on CI with Xcode 15
        # if [[ "${{ inputs.test_target }}" = "@@//examples:lottie_ios_example_test_bazel_.bazelversion" ]] ||
        #    [[ "${{ inputs.test_target }}" = "@@//examples:messagekit_example_test_bazel_.bazelversion" ]] ||
        #    [[ "${{ inputs.test_target }}" = "@@//examples:resources_example_test_bazel_.bazelversion" ]] ||
        #    [[ "${{ inputs.test_target }}" = "@@//examples:shake_ios_example_test_bazel_.bazelversion" ]]; then
        #   sudo xcode-select -s /Applications/Xcode_14.3.1.app/Contents/Developer
        # fi
        # if [[ "${{ inputs.test_target }}" = "@@//examples:firebase_example_test_bazel_.bazelversion" ]]; then
        #   sudo xcode-select -s /Applications/Xcode_15.0.1.app/Contents/Developer
        # fi
    # - name: Override Xcode Version
    #   shell: bash
    #   run: |
        # # GH762: Investigate why these examples timeout on CI with Xcode 15
        # if [[ "${{ inputs.test_target }}" = "@@//examples:lottie_ios_example_test_bazel_.bazelversion" ]] ||
        #    [[ "${{ inputs.test_target }}" = "@@//examples:messagekit_example_test_bazel_.bazelversion" ]] ||
        #    [[ "${{ inputs.test_target }}" = "@@//examples:resources_example_test_bazel_.bazelversion" ]] ||
        #    [[ "${{ inputs.test_target }}" = "@@//examples:shake_ios_example_test_bazel_.bazelversion" ]]; then
        #   sudo xcode-select -s /Applications/Xcode_14.3.1.app/Contents/Developer
        # fi
        # # TODO: Migrate all CI jobs to Xcode 15.2
        # if [[ "${{ inputs.test_target }}" = "@@//examples:stripe_example_test_bazel_.bazelversion" ]]; then
        #   sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer
        # fi
    - name: Confirm Xcode Version
      shell: bash
      run: |
        # Print used Xcode version
        xcode-select -print-path
        xcodebuild -version
    - uses: cgrindel/gha_set_up_bazel@v1
      with:
        repo_name: ${{ inputs.repo_name }}
    # As of macos-13 runner, go was not on the PATH. This resulted in bazel run 
    # //:go_update_repos failing.
    - uses: actions/setup-go@v5
      with:
        go-version: ">=1.20.0"
