#!/usr/bin/env bash

set -euo pipefail

# Use the Bazel binary specified by the integration test. Otherise, fall back
# to bazel.
bazel="${BIT_BAZEL_BINARY:-bazel}"

# Ensure that it builds and tests pass
"${bazel}" test //...
