#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail

# Use the Bazel binary specified by the integration test. Otherise, fall back
# to bazel.
bazel="${BIT_BAZEL_BINARY:-bazel}"

# Ensure that it builds and the Swift import resolves to the module declared in
# Yoga's explicit module map.
"${bazel}" test //...
"${bazel}" run //:yoga_example
