#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null && pwd)"

assert_match() {
  local pattern=${1}
  local actual="${2}"
  local err_msg="Expected to match. pattern: ${pattern}, actual: ${actual}"
  [[ "${actual}" =~ ${pattern} ]] || (echo >&2 "${err_msg}" && exit 1)
}

# Run update build files
bazel run //:tidy

# Ensure that it builds
bazel test //...

# Run PrintStuff
output="$(bazel run //Sources/PrintStuff)"
assert_match "My deque colors" "${output}" 
