package swift

const (
	// protoLibraryTargetNameSuffix is the suffix applied to the names of proto_library
	// targets generated by the gazelle plugin.
	protoLibraryTargetNameSuffix = "_proto"

	// swiftProtoLibraryTargetNameSuffix is the suffix applied to the names of swift_proto_library
	// targets generated by the gazelle plugin.
	swiftProtoLibraryTargetNameSuffix = "_swift_proto"
)
