package swift

import (
	"sort"
	"strings"

	"github.com/bazelbuild/bazel-gazelle/config"
	"github.com/bazelbuild/bazel-gazelle/language"
	"github.com/bazelbuild/bazel-gazelle/language/proto"
	"github.com/bazelbuild/bazel-gazelle/rule"
	"golang.org/x/text/cases"

	lang "golang.org/x/text/language"
)

// RulesFromProtos returns the Bazel build rule declarations for the provided source files.
func RulesFromProtos(
	args language.GenerateArgs,
	generateSwiftProtoLibraries bool,
	generateSwiftProtoLibraryGRPCFlavors []string,
	swiftProtoCompilers map[string]string,
	generatePascalCaseModuleNames bool,
) []*rule.Rule {

	// Extract information about proto library and swift proto library targets generated by languages.
	// This is a collection of proto_library rule names that have a corresponding
	// swift_proto_library rule already generated.
	var protoLibraryTargetNames []string
	protoLibraryTargetNamesToProtoPackages := make(map[string]proto.Package)
	for _, r := range args.OtherGen {
		if r.Kind() != "proto_library" {
			continue
		}
		protoPackage := r.PrivateAttr(proto.PackageKey).(proto.Package)
		protoLibraryTargetNames = append(protoLibraryTargetNames, r.Name())
		protoLibraryTargetNamesToProtoPackages[r.Name()] = protoPackage
	}
	sort.Strings(protoLibraryTargetNames)
	var emptyProtoLibraryTargetNames []string
	for _, r := range args.OtherEmpty {
		if r.Kind() == "proto_library" {
			emptyProtoLibraryTargetNames = append(emptyProtoLibraryTargetNames, r.Name())
		}
	}
	sort.Strings(emptyProtoLibraryTargetNames)

	// Generate the rules from proto packages:
	var rules []*rule.Rule
	for protoLibraryTargetName, protoPackage := range protoLibraryTargetNamesToProtoPackages {
		rs := generateRuleFromProtoPackage(
			args,
			protoLibraryTargetName,
			protoPackage,
			generateSwiftProtoLibraries,
			generateSwiftProtoLibraryGRPCFlavors,
			swiftProtoCompilers,
			generatePascalCaseModuleNames,
		)
		rules = append(rules, rs...)
	}

	return rules
}

func pascalCaseModuleName(snakeCaseModuleName string) string {
	moduleNameComponents := strings.Split(snakeCaseModuleName, "_")
	caser := cases.Title(lang.English)
	pascalCaseModuleName := ""
	for _, component := range moduleNameComponents {
		pascalCaseModuleName += caser.String(component)
	}

	return pascalCaseModuleName
}

func deriveSwiftProtoLibraryTargetNameAndModuleName(
	protoLibraryTargetName string,
	protoPackage proto.Package,
	protoFlavor string,
	generatePascalCaseModuleNames bool,
) (string, string) {
	protoLibraryTargetNamePrefix := strings.TrimSuffix(protoLibraryTargetName, protoLibraryTargetNameSuffix)

	// Determine the swift_proto_library target name:
	swiftProtoLibraryTargetName := protoLibraryTargetNamePrefix
	swiftProtoLibraryTargetName += "_" + protoFlavor

	// Determine the swift_proto_library module name:
	swiftProtoLibraryModuleName := protoLibraryTargetNamePrefix + strings.TrimSuffix(strings.TrimPrefix(protoFlavor, "swift"), "_proto")
	if generatePascalCaseModuleNames {
		swiftProtoLibraryModuleName = pascalCaseModuleName(swiftProtoLibraryModuleName)
	}

	return swiftProtoLibraryTargetName, swiftProtoLibraryModuleName
}

// These protos are statically linked into the SwiftProtobuf module:
// https://github.com/apple/swift-protobuf/blob/main/Sources/SwiftProtobufPluginLibrary/SwiftProtobufInfo.swift
var wellKnownTypeProtoImports map[string]struct{} = map[string]struct{}{
	"google/protobuf/timestamp.proto":      {},
	"google/protobuf/field_mask.proto":     {},
	"google/protobuf/api.proto":            {},
	"google/protobuf/duration.proto":       {},
	"google/protobuf/struct.proto":         {},
	"google/protobuf/wrappers.proto":       {},
	"google/protobuf/source_context.proto": {},
	"google/protobuf/any.proto":            {},
	"google/protobuf/type.proto":           {},
	"google/protobuf/empty.proto":          {},
	"google/protobuf/descriptor.pro":       {},
}

func isWellKnownTypeProtoImport(protoImport string) bool {
	_, ok := wellKnownTypeProtoImports[protoImport]
	return ok
}

func generateRuleFromProtoPackage(
	args language.GenerateArgs,
	protoLibraryTargetName string,
	protoPackage proto.Package,
	generateSwiftProtoLibraries bool,
	generateSwiftProtoLibraryGRPCFlavors []string,
	swiftProtoCompilers map[string]string,
	generatePascalCaseModuleNames bool,
) []*rule.Rule {

	// Determine whether we should set visibility on the target:
	shouldSetVisibility := shouldSetVisibility(args)

	// Create the swift proto package:
	swiftProtoPackage := SwiftProtoPackage{
		Dir:          args.Dir,
		Rel:          args.Rel,
		ProtoPackage: protoPackage,
	}

	// Build the list of protos imported by the proto package which we need to resolve:
	gazelleImports := []string{}
	for protoImport := range protoPackage.Imports {
		if isWellKnownTypeProtoImport(protoImport) {
			// Skip these protos because they're statically linked into SwiftProtobuf.
			continue
		} else {
			// These are just the paths to the specific protos to import, e.g.:
			// "protos/echoservice/messages/echo_messages.proto"
			// We need to defer resolving these to swift_proto_library targets until initial generation is complete.
			gazelleImports = append(gazelleImports, protoImport)
		}
	}

	// Generate the swift_proto_library:
	rules := []*rule.Rule{}
	if protoPackage.HasServices {

		// Generate the targets for the requested variants:
		for _, protoFlavor := range generateSwiftProtoLibraryGRPCFlavors {

			// Determine the target name and module name for the swift_proto_library target:
			swiftProtoLibraryTargetName, swiftProtoLibraryModuleName := deriveSwiftProtoLibraryTargetNameAndModuleName(
				protoLibraryTargetName,
				protoPackage,
				protoFlavor,
				generatePascalCaseModuleNames,
			)

			// Generate the swift_proto_library target for the flavor:
			swiftProtoLibrary := rule.NewRule("swift_proto_library", swiftProtoLibraryTargetName)
			swiftProtoLibrary.SetAttr(ModuleNameAttrName, swiftProtoLibraryModuleName)
			swiftProtoLibrary.SetAttr("protos", []string{":" + protoLibraryTargetName})
			swiftProtoLibrary.SetAttr("compilers", []string{swiftProtoCompilers[protoFlavor]})
			swiftProtoLibrary.SetPrivateAttr(config.GazelleImportsKey, gazelleImports)
			swiftProtoLibrary.SetPrivateAttr(SwiftProtoPackageKey, swiftProtoPackage)
			setVisibilityAttr(swiftProtoLibrary, shouldSetVisibility, []string{"//visibility:public"})
			rules = append(rules, swiftProtoLibrary)
		}
	} else if generateSwiftProtoLibraries {

		// Determine the target name and module name for the swift_proto_library target:
		swiftProtoLibraryTargetName, swiftProtoLibraryModuleName := deriveSwiftProtoLibraryTargetNameAndModuleName(
			protoLibraryTargetName,
			protoPackage,
			"swift_proto",
			generatePascalCaseModuleNames,
		)

		// Generate the standard, non-GRPC swift_proto_library target:
		swiftProtoLibrary := rule.NewRule("swift_proto_library", swiftProtoLibraryTargetName)
		swiftProtoLibrary.SetAttr(ModuleNameAttrName, swiftProtoLibraryModuleName)
		swiftProtoLibrary.SetAttr("protos", []string{":" + protoLibraryTargetName})
		swiftProtoLibrary.SetAttr("compilers", []string{swiftProtoCompilers["swift_proto"]})
		swiftProtoLibrary.SetPrivateAttr(config.GazelleImportsKey, gazelleImports)
		swiftProtoLibrary.SetPrivateAttr(SwiftProtoPackageKey, swiftProtoPackage)
		setVisibilityAttr(swiftProtoLibrary, shouldSetVisibility, []string{"//visibility:public"})
		rules = append(rules, swiftProtoLibrary)
	}

	return rules
}
