#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail

# NOTE: This is a placeholder. The firebase examples do not support a clean
# test because some of the targets have been marked as 'manual'.
