#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null && pwd)"

# Remove all build files
find "${script_dir}" \
  -name "BUILD.bazel" \
  -not -path "${script_dir}/third_party/*" \
  -exec rm {} \;

# Remove the SPM build folder
rm -rf .build

# Add back a minimal build file at the root
cat > "${script_dir}/BUILD.bazel"  <<-EOF
load("@bazel_gazelle//:def.bzl", "gazelle", "gazelle_binary")
load("@cgrindel_bazel_starlib//bzltidy:defs.bzl", "tidy")
load("@rules_swift_package_manager//swiftpkg:defs.bzl", "swift_update_packages")

tidy(
    name = "tidy",
    targets = [
        ":swift_update_pkgs",
        ":update_build_files",
    ],
)

# MARK: - Gazelle

# Ignore the Swift build folder
# gazelle:exclude .build

gazelle_binary(
    name = "gazelle_bin",
    languages = [
        "@bazel_skylib_gazelle_plugin//bzl",
        "@rules_swift_package_manager//gazelle",
    ],
)

gazelle(
    name = "update_build_files",
    gazelle = ":gazelle_bin",
)

swift_update_packages(
    name = "swift_update_pkgs",
    gazelle = ":gazelle_bin",
    generate_swift_deps_for_workspace = False,
    print_bzlmod_stanzas = True,
    update_bzlmod_stanzas = True,
)

alias(
    name = "swiftformat",
    # This is the executable product.
    # FYI. The identity for SwiftFormat in the swift package dump-package is
    # lowercase. That is why it is lowercase here.
    actual = "@swiftpkg_swiftformat//:swiftformat",
)
EOF
