#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail

# Use the Bazel binary specified by the integration test. Otherise, fall back 
# to bazel.
bazel="${BIT_BAZEL_BINARY:-bazel}"

# DEBUG BEGIN
echo >&2 "*** CHUCK $(basename "${BASH_SOURCE[0]}") bazel: ${bazel}" 
# bazel_path="$( which bazel )"
# echo >&2 "*** CHUCK $(basename "${BASH_SOURCE[0]}") bazel_path: ${bazel_path}" 
env | sort >&2
set -x
# DEBUG END

# Execute the Bazel command
"${bazel}" "${@}"
