#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null && pwd)"

# Remove all build files
find "${script_dir}" \
  -name "BUILD.bazel" \
  -not -path "${script_dir}/third_party/*" \
  -exec rm {} \;

# Remove the SPM build folder
rm -rf .build

# Add back a minimal build file at the root
cat > "${script_dir}/BUILD.bazel"  <<-EOF
load("@bazel_gazelle//:def.bzl", "gazelle", "gazelle_binary")
load("@cgrindel_bazel_starlib//bzltidy:defs.bzl", "tidy")

# MARK: - Gazelle

# Ignore the Swift build folder
# gazelle:exclude .build

# gazelle:swift_default_module_name objc_code

gazelle_binary(
    name = "gazelle_bin",
    languages = [
        "@bazel_skylib_gazelle_plugin//bzl",
        "@rules_swift_package_manager//gazelle",
    ],
)

gazelle(
    name = "update_build_files",
    gazelle = ":gazelle_bin",
)

sh_test(
    name = "objc_code_test",
    srcs = ["objc_code_test.sh"],
    data = [":objc_code"],
    deps = ["@bazel_tools//tools/bash/runfiles"],
)
EOF
